name: qemu-minimal-shellcheck

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.sh'
      - 'qemu/**'
      - 'libvirt/**'
      - 'scripts/**'
  push:
    branches:
      - main
    paths:
      - '**.sh'
      - 'qemu/**'
      - 'libvirt/**'
      - 'scripts/**'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2
      
      - name: Run ShellCheck
        run: |
          shellcheck -S error \
            qemu/gen-vm \
            qemu/run-vm \
            qemu/run-vm-cxl-nvme \
            qemu/vfio-setup \
            libvirt/virt-install-ubuntu \
            libvirt/virt-clone-many \
            libvirt/create-gcp-nested \
            libvirt/create-nvme \
            libvirt/create-raid

