name: qemu-minimal-shellcheck

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.sh'
      - 'qemu/**'
      - 'libvirt/**'
  push:
    branches:
      - main
    paths:
      - '**.sh'
      - 'qemu/**'
      - 'libvirt/**'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2
      
      - name: Run ShellCheck
        run: |
          shellcheck -S error \
            qemu/gen-vm \
            qemu/run-vm \
            libvirt/create-nvme \
            libvirt/virt-install-ubuntu

